unique_ids:
  assets:
    standard-page.html: XSY77DGWRPPN6TZGZVW7JJCXXPWNDJGJ
    theme.css: BP3KTYKGZQ54CK7D4DM7EXYV34IBSRMI
  forms:
    BmwAutohandel: YJYHKMFTNUHWNV7J3G3BJKFBYIMGNYBR
  modules: {}
  scripts: {}
  server_modules: {}
